steps:

# This step stops the nfs pod
- name: 'gcr.io/cloud-builders/kubectl'
  id: Stop Pod
  args:
    - 'scale'
    - 'deploy'
    - 'nfs-dev'
    - '--replicas=0'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'  

# This step deploys the application in Kubernetes
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=dev.yaml
  - --image=gcr.io/$PROJECT_ID/nfs:$_SHORT_SHA
  - --location=us-east1-b
  - --cluster=cluster-1

# This step starts the nfs pod
- name: 'gcr.io/cloud-builders/kubectl'
id: Scale Pod
args:
  - 'scale'
  - 'deploy'
  - 'nfs-dev'
  - '--replicas=1'
env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'    