apiVersion: v1
kind: Service
metadata:
  name: nfs
  labels:
    app: nfs
spec:
  ports:
  - port: 2049
    name: nfs
  selector:
    app: nfs
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs
spec:
  serviceName: nfs
  replicas: 1
  selector:
    matchLabels:
      app: nfs
  template:
    metadata:
      labels:
        app: nfs
    spec:
      containers:
      - name: nfs
        image: gcr.io/constellation-275522/nfs
        ports:
        - containerPort: 2049
          name: nfs
        resources:
          limits:
            cpu: ".5"
            memory: "500Mi"
          requests:
            cpu: ".25"
            memory: "250Mi"
        volumeMounts:
        - name: nfs
          mountPath: /nfsshare
        livenessProbe:
          tcpSocket:
            port: 2049
          initialDelaySeconds: 3
          periodSeconds: 3
  volumeClaimTemplates:
  - metadata:
      name: nfs
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi

   
